### PR TITLE
convert ansible inventory file to /etc/hosts file

### PR DESCRIPTION
**Pull request by bengland2**
Since all nodes in ceph-linode clusters have different hostnames each time the cluster is provisioned, this makes it more difficult to write scripting (except for ansible playbooks/commands) or login to hosts.  This script converts an ansible inventory file (generated by ceph-linode linode-launch.py) to a /etc/hosts file so that you can then do commands like: ssh mon-000 ceph -s.

### CODE REVIEW

**Comment by batrick** [comment]
ben, looks like you left the old file behind. Can you squash the commits?

**Comment by bengland2** [comment]
I think I've fixed the problem, can you squash the commits together?  I was told there is a checkbox for this in github when merging.  If not, how do I do it, other than submitting a brand new PR?

**Comment by batrick** [comment]
Here's what I usually do:

````
# have a clean working copy of your branch:
$ git status # no modified files
$ git reset HEAD^ # do this until `git log` no longer shows your commiits
$ git add -u # add all your changes
$ git status # make sure you didn't miss anything (like new files)
$ git commit # make one commit
$ git push origin <yourbranch> --force # force push it to your github branch, PR will be updated
````

**Comment by bengland2** [comment]
Done

**Pull request merged**
